replicaCount: 1
image:
  repository: cloudpossedemo/front-end
  tag: '{{ (datasource "semver").version }}'
  pullPolicy: IfNotPresent
deployment:
  ## Deployment annotations
  # annotations:
  #   name: value
  replicas:
  ## Replicas annotations
  #   annotations:
  ##    Read more about kube2iam to provide access to s3 https://github.com/jtblin/kube2iam
  #     iam.amazonaws.com/role: role-arn
service:
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
  # annotations:
  #   foo.io/bar: "true"
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 80m
    memory: 64Mi
## Ingress for load balancer
# ingress:
# - name: "default"
## Ingress labels
##
#   labels:
#     dns: "route53"

## Ingress annotations
##
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     kubernetes.io/tls-acme: "true"

## Ingress hostnames
## Must be provided if Ingress is enabled
##
#   hosts:
#     "domain.com": /
#     "www.domain.com": /

## Ingress TLS configuration
## Secrets must be manually created in the namespace
##
#   tls:
#   - secretName: server-tls
#     hosts:
#     - domain.com
