language: node_js

sudo: required

node_js:
  - "4.8.1"

services:
  - docker

before_install:
  - sudo apt-get install -y make
  - make deps

install:
  - npm install

env:
  - GROUP=kenazk COMMIT="${TRAVIS_COMMIT}" TAG=latest REPO=front-end NEBULA_WORKFLOW=puppetize-demo-app-1

script:
  - set -e
  - if [ -z "${DOCKER_PASS}" ]; then echo "Build triggered by external PR. Skipping docker push" && exit 0; fi
  - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
  - ./scripts/build.sh
  - ./scripts/push.sh
  - chmod +x ./scripts/deploy.sh
  - ./scripts/deploy.sh